title: First Jekyll-based GitHub Pages site!
author: Ian Graham
description: > # this means to ignore newlines until "baseurl:"
  This is my first Jekyll-based GitHub Page, built during the GitHub Pages
  tutorial.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  iggraham # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
